[package]
name = "carrick"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
derivative = "2.2.0"
matchit = "0.8.6"
regex = "1.11.1"
semver = "1.0"
serde = "1.0.219"
serde_json = "1.0.140"
swc_common = { version = "8.0.1", features = ["tty-emitter"] }
swc_ecma_ast = "8.1.0"
swc_ecma_codegen = "11.0.0"
swc_ecma_parser = "11.0.0"
swc_ecma_visit = "8.0.0"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.0"
