//! TypeSidecar - Rust interface to the Node.js type extraction sidecar.
//!
//! Note: Some public APIs are not yet used but will be integrated in Phase 3.
#![allow(dead_code)]
//!
//! This module provides a non-blocking interface to spawn and communicate with
//! the type-sidecar process. The sidecar runs ts-morph and dts-bundle-generator
//! to extract TypeScript types from source code.
//!
//! Key design principles:
//! - **Non-blocking spawn**: The sidecar spawns immediately, initialization happens in background
//! - **Parallel startup**: SWC scanning and LLM analysis can proceed while sidecar initializes
//! - **JSON message protocol**: All communication is via stdin/stdout JSON messages

use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::io::{BufRead, BufReader, Write};
use std::path::Path;
use std::process::{Child, ChildStdin, ChildStdout, Command, Stdio};
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, Instant};
use tracing::{debug, info};

// ============================================================================
// Sidecar State
// ============================================================================

/// State of the sidecar process
#[derive(Debug, Clone, PartialEq)]
pub enum SidecarState {
    /// Process has been spawned but not yet initialized
    Spawning,
    /// Init request sent, waiting for ready response
    Initializing,
    /// Sidecar is ready to process requests
    Ready,
    /// Sidecar failed to initialize or encountered an error
    Failed(String),
}

// ============================================================================
// Request Types (matching TypeScript types)
// ============================================================================

/// Kind of type inference to perform
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum InferKind {
    /// Get return type of a function
    FunctionReturn,
    /// Get type of an expression
    Expression,
    /// Get return type of a call expression
    CallResult,
    /// Get type of a variable declaration
    Variable,
    /// Find response body (.json()/.send()/ctx.body)
    ResponseBody,
    /// Find request body (req.body/ctx.request.body or call payloads)
    RequestBody,
    /// Function return for the signature hint — NO Promise/wrapper unwrapping
    SignatureReturn,
    /// Type of a single named parameter (explicit or contextually inferred)
    FunctionParam,
}

/// A rule for unwrapping machinery/wrapper types to extract payload types.
/// Generated by the cloud's `extraction_config` task from the repo's
/// detected frameworks, data fetchers, and dependency list; consumed by the
/// sidecar's agent-informed unwrap engine (`type-inferrer.ts`).
///
/// Wire format is camelCase to match the sidecar's `ExtractionRule`
/// (`src/sidecar/src/types.ts`). `payload_generic_index` must be omitted
/// (not null) when absent — the sidecar validator rejects null.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ExtractionRule {
    /// Exact wrapper type/symbol names to unwrap (e.g. `AxiosResponse`).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub wrapper_symbols: Vec<String>,
    /// Method/property names that mark a machinery type (e.g. `statusCode`).
    /// Only applied together with `origin_module_globs`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub machinery_indicators: Vec<String>,
    /// Module-path globs the wrapper's declaration must come from. Multiple
    /// candidate globs are allowed (ambient/global machinery types ship
    /// several plausible origins); entries that match nothing are no-ops.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub origin_module_globs: Vec<String>,
    /// Index of the generic type argument holding the payload (default 0).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payload_generic_index: Option<u32>,
    /// Property path to the payload when generics are unavailable
    /// (e.g. `["data"]` for `AxiosResponse.data`).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub payload_property_path: Vec<String>,
    /// Recursively unwrap nested wrappers (`Promise<AxiosResponse<T>>` → `T`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unwrap_recursively: Option<bool>,
    /// Maximum unwrap depth when `unwrap_recursively` is set (sidecar
    /// defaults to 4).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_depth: Option<u32>,
}

/// Agent-generated configuration for extracting payload types from
/// machinery wrappers.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
pub struct ExtractionConfig {
    pub rules: Vec<ExtractionRule>,
}

/// Request for a specific symbol to be bundled
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SymbolRequest {
    /// The name of the symbol (type, interface, class, etc.)
    pub symbol_name: String,
    /// The source file path (relative to repo root)
    pub source_file: String,
    /// Optional alias for the exported type
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    /// Wrap the bundled symbol in this many TS array levels (#248): a GraphQL
    /// SDL producer field `[Order!]!` backed by `interface Order` bundles `Order`
    /// with `array_depth: 1` so the sidecar emits `Order[]` — the element type
    /// carries the shape, the SDL list marker carries the depth. Omitted/`0`
    /// bundles the symbol as-is (the HTTP/socket/consumer default).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub array_depth: Option<u32>,
    /// Deterministic borrow witness from the scanner's AST pre-pass (pub/sub
    /// two-anchor arbitration, #413 / the #403/#359 borrow-class lineage):
    /// `true` means the file's own annotations testify that `symbol_name`
    /// structurally cannot be the payload this request's alias stands for —
    /// the payload binding is annotated with a type that never mentions the
    /// symbol, while the symbol annotates a DIFFERENT binding in the same
    /// file (where the model borrowed it from). Only
    /// `collect_pubsub_type_requests` ever sets this; HTTP/socket/GraphQL
    /// requests always carry `false`, so `demote_witnessed_borrowed_anchors`
    /// is structurally inert for every non-pub/sub path. Scanner-internal:
    /// never serialized to the sidecar.
    #[serde(skip)]
    pub payload_borrow_witness: bool,
}

/// Request for type inference at a specific location
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InferRequestItem {
    /// Path to the file (relative to repo root)
    pub file_path: String,
    /// Line number (1-based) where inference should occur
    pub line_number: u32,
    /// Start byte offset of the target expression (from SWC spans)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub span_start: Option<u32>,
    /// End byte offset of the target expression (from SWC spans)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub span_end: Option<u32>,
    /// Verbatim expression text to locate in source (from Gemini)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expression_text: Option<String>,
    /// Line number where the expression starts (from Gemini)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expression_line: Option<u32>,
    /// The kind of inference to perform
    pub infer_kind: InferKind,
    /// Optional alias for the inferred type
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    /// Target parameter name for `FunctionParam` inference.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub param_name: Option<String>,
}

// ============================================================================
// Internal Request Messages
// ============================================================================

#[derive(Debug, Serialize)]
#[serde(tag = "action")]
enum SidecarRequest {
    #[serde(rename = "init")]
    Init {
        request_id: String,
        repo_root: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        tsconfig_path: Option<String>,
    },
    #[serde(rename = "bundle")]
    Bundle {
        request_id: String,
        symbols: Vec<SymbolRequest>,
    },
    #[serde(rename = "infer")]
    Infer {
        request_id: String,
        requests: Vec<InferRequestItem>,
        #[serde(skip_serializing_if = "Option::is_none")]
        extraction_config: Option<ExtractionConfig>,
    },
    #[serde(rename = "resolve_definitions")]
    ResolveDefinitions {
        request_id: String,
        bundled_dts: String,
        aliases: Vec<String>,
    },
    #[serde(rename = "health")]
    Health { request_id: String },
    #[serde(rename = "shutdown")]
    Shutdown { request_id: String },
}

// ============================================================================
// Response Types (matching TypeScript types)
// ============================================================================

/// Source location information for a type
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceLocation {
    /// File path relative to repo root
    pub file_path: String,
    /// Start line (1-based)
    pub start_line: u32,
    /// End line (1-based)
    pub end_line: u32,
    /// Start column (0-based)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_column: Option<u32>,
    /// End column (0-based)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_column: Option<u32>,
}

/// An entry in the type manifest
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManifestEntry {
    /// The alias or original name of the type
    pub alias: String,
    /// The original symbol name
    pub original_name: String,
    /// The source file where the type was found
    pub source_file: String,
    /// The full type definition string
    pub type_string: String,
    /// Whether this was an explicit annotation or inferred
    pub is_explicit: bool,
}

/// An inferred type result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InferredType {
    /// The alias for this type (generated if not provided)
    pub alias: String,
    /// The full TypeScript type string
    pub type_string: String,
    /// Whether the type was explicitly annotated in source
    pub is_explicit: bool,
    /// Source location information
    pub source_location: SourceLocation,
    /// The kind of inference that was performed
    pub infer_kind: InferKind,
    /// Deterministic source symbol of the resolved type (`Payment`), from the
    /// sidecar's `getSymbol() || getAliasSymbol()` name with TS/lib globals
    /// filtered out. Fills the manifest anchor (`primary_type_symbol`) when the
    /// LLM emitted none, removing the anchor's sole dependency on the model.
    /// For an array type this is the ELEMENT's symbol (`TimelineEvent` for
    /// `TimelineEvent[]`), with the peeled levels reported in `array_depth`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub primary_type_symbol: Option<String>,
    /// Array levels the resolved type wraps around `primary_type_symbol`
    /// (#306): `TimelineEvent[]` reports symbol `TimelineEvent` + depth 1.
    /// `resolve_all_types` copies this onto an explicit `SymbolRequest` for the
    /// same alias/symbol so the bundle keeps the use-site's array-ness instead
    /// of the bare element. Absent when 0 or when there is no anchor symbol.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub array_depth: Option<u32>,
    /// Declaration file (absolute path) of `primary_type_symbol`, reported by
    /// the pub/sub infer kinds (`function_param`, `expression`) only (#413).
    /// `demote_witnessed_borrowed_anchors` uses it to re-aim a demoted
    /// explicit `SymbolRequest`: the bundler resolves a symbol only against
    /// declarations IN the request's `source_file`, and the inference is the
    /// only party that knows where the tsc-witnessed payload type lives.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub primary_type_symbol_source: Option<String>,
}

/// Information about a symbol that failed to resolve
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SymbolFailure {
    /// The symbol that failed
    pub symbol_name: String,
    /// The source file where it was supposed to be
    pub source_file: String,
    /// Reason for the failure
    pub reason: String,
}

/// Response from the sidecar
#[derive(Debug, Clone, Deserialize)]
pub struct SidecarResponse {
    /// Echo of the request_id
    pub request_id: String,
    /// Response status
    pub status: String,
    /// Initialization time in milliseconds (for init/health)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub init_time_ms: Option<u64>,
    /// Bundled .d.ts content (for bundle)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dts_content: Option<String>,
    /// Manifest entries (for bundle)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub manifest: Option<Vec<ManifestEntry>>,
    /// Symbol failures (for bundle)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub symbol_failures: Option<Vec<SymbolFailure>>,
    /// Inferred types (for infer)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inferred_types: Option<Vec<InferredType>>,
    /// Resolved definitions (for resolve_definitions)
    #[serde(default)]
    pub definitions: Option<Vec<ResolvedDefinitionResult>>,
    /// Error messages
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<String>>,
}

/// A single resolved type definition from the sidecar
#[derive(Debug, Clone, Deserialize)]
pub struct ResolvedDefinitionResult {
    pub type_alias: String,
    /// Original declaration text as written
    pub definition: String,
    /// Compiler-expanded form with all types fully inlined
    pub expanded: String,
}

// ============================================================================
// Combined Result Type
// ============================================================================

/// Result of resolving all types (explicit + inferred)
#[derive(Debug, Clone)]
pub struct TypeResolutionResult {
    /// The bundled .d.ts content (explicit types)
    pub dts_content: Option<String>,
    /// Manifest of explicit types
    pub explicit_manifest: Vec<ManifestEntry>,
    /// Inferred types
    pub inferred_types: Vec<InferredType>,
    /// Failures for explicit symbols
    pub symbol_failures: Vec<SymbolFailure>,
    /// General errors
    pub errors: Vec<String>,
}

// ============================================================================
// TypeSidecar Implementation
// ============================================================================

/// TypeSidecar - Manages communication with the Node.js type extraction sidecar.
///
/// # Example
///
/// ```no_run
/// use carrick::services::TypeSidecar;
/// use std::path::Path;
/// use std::time::Duration;
///
/// // Spawn the sidecar (non-blocking)
/// let mut sidecar = TypeSidecar::spawn(Path::new("./node_modules/.bin/type-sidecar")).unwrap();
///
/// // Start initialization (non-blocking)
/// sidecar.start_init(Path::new("/path/to/repo"), None);
///
/// // ... do other work while sidecar initializes ...
///
/// // Wait for sidecar to be ready
/// sidecar.wait_ready(Duration::from_secs(30)).unwrap();
///
/// // Now resolve types
/// let result = sidecar.resolve_types(&[]).unwrap();
/// ```
pub struct TypeSidecar {
    /// Child process handle
    child: Child,
    /// Stdin for sending requests (wrapped in mutex for thread safety)
    stdin: Mutex<ChildStdin>,
    /// Stdout for reading responses (wrapped in mutex for thread safety)
    stdout: Mutex<BufReader<ChildStdout>>,
    /// Current state of the sidecar
    state: Arc<Mutex<SidecarState>>,
    /// Time when spawn() was called
    spawn_time: Instant,
    /// Request ID counter
    request_counter: Mutex<u64>,
}

impl TypeSidecar {
    /// Spawn the sidecar process.
    ///
    /// This returns immediately after spawning - the sidecar process starts
    /// initializing in the background. Call `start_init()` to begin TypeScript
    /// project initialization, then `wait_ready()` when you need to use it.
    ///
    /// # Arguments
    /// * `sidecar_path` - Path to the sidecar executable (node script)
    ///
    /// # Returns
    /// A new `TypeSidecar` instance in the `Spawning` state.
    pub fn spawn(sidecar_path: &Path) -> Result<Self, SidecarError> {
        let spawn_time = Instant::now();

        debug!("[type_sidecar] Spawning sidecar from: {:?}", sidecar_path);

        // Spawn the Node.js process
        let mut child = Command::new("node")
            .arg(sidecar_path)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped()) // Capture stderr, pipe through tracing
            .spawn()
            .map_err(|e| SidecarError::SpawnFailed(e.to_string()))?;

        let stdin = child
            .stdin
            .take()
            .ok_or_else(|| SidecarError::SpawnFailed("Failed to get stdin".to_string()))?;

        let stdout = child
            .stdout
            .take()
            .ok_or_else(|| SidecarError::SpawnFailed("Failed to get stdout".to_string()))?;

        // Pipe sidecar stderr through tracing on a background thread
        if let Some(stderr) = child.stderr.take() {
            thread::spawn(move || {
                let reader = BufReader::new(stderr);
                for line in reader.lines().map_while(Result::ok) {
                    if !line.trim().is_empty() {
                        debug!("{}", line);
                    }
                }
            });
        }

        debug!(
            "[type_sidecar] Sidecar spawned in {:?}",
            spawn_time.elapsed()
        );

        Ok(Self {
            child,
            stdin: Mutex::new(stdin),
            stdout: Mutex::new(BufReader::new(stdout)),
            state: Arc::new(Mutex::new(SidecarState::Spawning)),
            spawn_time,
            request_counter: Mutex::new(0),
        })
    }

    /// Start initialization of the TypeScript project.
    ///
    /// This sends the init request and returns immediately. The sidecar
    /// will process the initialization in the background. Use `wait_ready()`
    /// to block until initialization is complete.
    ///
    /// # Arguments
    /// * `repo_root` - Path to the repository root
    /// * `tsconfig_path` - Optional path to tsconfig.json (relative to repo root)
    pub fn start_init(&self, repo_root: &Path, tsconfig_path: Option<&str>) {
        let repo_root_str = repo_root.to_string_lossy().to_string();
        let tsconfig = tsconfig_path.map(String::from);

        // Update state to Initializing
        {
            let mut state = self.state.lock().unwrap();
            *state = SidecarState::Initializing;
        }

        debug!("[type_sidecar] Starting init for repo: {}", repo_root_str);

        // Send init request
        let request = SidecarRequest::Init {
            request_id: self.next_request_id(),
            repo_root: repo_root_str,
            tsconfig_path: tsconfig,
        };

        if let Err(e) = self.send_request(&request) {
            let mut state = self.state.lock().unwrap();
            *state = SidecarState::Failed(format!("Failed to send init: {}", e));
        }
    }

    /// Check if the sidecar is ready (non-blocking).
    ///
    /// This checks the current state without waiting.
    pub fn is_ready(&self) -> bool {
        let state = self.state.lock().unwrap();
        *state == SidecarState::Ready
    }

    /// Get the current state of the sidecar.
    pub fn get_state(&self) -> SidecarState {
        self.state.lock().unwrap().clone()
    }

    /// Wait for the sidecar to become ready.
    ///
    /// This blocks until the sidecar is ready or the timeout expires.
    /// If `start_init()` was called, this will wait for the init response.
    ///
    /// # Arguments
    /// * `timeout` - Maximum time to wait
    ///
    /// # Returns
    /// Ok(()) if ready, Err if timeout or failure.
    pub fn wait_ready(&self, timeout: Duration) -> Result<(), SidecarError> {
        let start = Instant::now();

        // If we're in Initializing state, read the init response
        {
            let state = self.state.lock().unwrap();
            if *state == SidecarState::Initializing {
                drop(state); // Release lock before reading

                // Read the init response
                match self.read_response_with_timeout(timeout) {
                    Ok(response) => {
                        let mut state = self.state.lock().unwrap();
                        if response.status == "ready" {
                            *state = SidecarState::Ready;
                            debug!(
                                "[type_sidecar] Sidecar ready (init_time: {:?}ms, total: {:?})",
                                response.init_time_ms,
                                self.spawn_time.elapsed()
                            );
                        } else {
                            let error = response
                                .errors
                                .map(|e| e.join("; "))
                                .unwrap_or_else(|| "Unknown error".to_string());
                            *state = SidecarState::Failed(error.clone());
                            return Err(SidecarError::InitFailed(error));
                        }
                    }
                    Err(e) => {
                        let mut state = self.state.lock().unwrap();
                        *state = SidecarState::Failed(e.to_string());
                        return Err(e);
                    }
                }
            }
        }

        // Poll state until ready or timeout
        while start.elapsed() < timeout {
            let state = self.state.lock().unwrap();
            match &*state {
                SidecarState::Ready => return Ok(()),
                SidecarState::Failed(e) => return Err(SidecarError::InitFailed(e.clone())),
                _ => {
                    drop(state);
                    thread::sleep(Duration::from_millis(10));
                }
            }
        }

        Err(SidecarError::Timeout)
    }

    /// Resolve explicit types by bundling symbols.
    ///
    /// # Arguments
    /// * `symbols` - Symbols to bundle
    ///
    /// # Returns
    /// The sidecar response with bundled types.
    pub fn resolve_types(
        &self,
        symbols: &[SymbolRequest],
    ) -> Result<SidecarResponse, SidecarError> {
        self.ensure_ready()?;

        if symbols.is_empty() {
            return Ok(SidecarResponse {
                request_id: "empty".to_string(),
                status: "success".to_string(),
                init_time_ms: None,
                dts_content: Some(String::new()),
                manifest: Some(vec![]),
                symbol_failures: None,
                inferred_types: None,
                definitions: None,
                errors: None,
            });
        }

        let request = SidecarRequest::Bundle {
            request_id: self.next_request_id(),
            symbols: symbols.to_vec(),
        };

        self.send_request(&request)?;
        self.read_response_with_timeout(Duration::from_secs(60))
    }

    /// Infer implicit types at specified locations.
    ///
    /// # Arguments
    /// * `requests` - Inference requests
    /// * `extraction_config` - Optional agent-generated unwrap rules
    ///
    /// # Returns
    /// The sidecar response with inferred types.
    pub fn infer_types(
        &self,
        requests: &[InferRequestItem],
        extraction_config: Option<&ExtractionConfig>,
    ) -> Result<SidecarResponse, SidecarError> {
        self.ensure_ready()?;

        if requests.is_empty() {
            return Ok(SidecarResponse {
                request_id: "empty".to_string(),
                status: "success".to_string(),
                init_time_ms: None,
                dts_content: None,
                manifest: None,
                symbol_failures: None,
                inferred_types: Some(vec![]),
                definitions: None,
                errors: None,
            });
        }

        let request = SidecarRequest::Infer {
            request_id: self.next_request_id(),
            requests: requests.to_vec(),
            extraction_config: extraction_config
                .filter(|config| !config.rules.is_empty())
                .cloned(),
        };

        self.send_request(&request)?;
        self.read_response_with_timeout(Duration::from_secs(60))
    }

    /// Resolve type definitions from bundled .d.ts content.
    ///
    /// For each alias, returns both the original declaration text and the
    /// compiler-expanded form with all types fully inlined.
    ///
    /// # Arguments
    /// * `bundled_dts` - The bundled .d.ts content
    /// * `aliases` - Type alias names to resolve
    pub fn resolve_definitions(
        &self,
        bundled_dts: &str,
        aliases: &[String],
    ) -> Result<Vec<ResolvedDefinitionResult>, SidecarError> {
        self.ensure_ready()?;

        if aliases.is_empty() {
            return Ok(vec![]);
        }

        let request = SidecarRequest::ResolveDefinitions {
            request_id: self.next_request_id(),
            bundled_dts: bundled_dts.to_string(),
            aliases: aliases.to_vec(),
        };

        self.send_request(&request)?;
        let response = self.read_response_with_timeout(Duration::from_secs(30))?;

        if response.status != "success" {
            let errors = response.errors.unwrap_or_default();
            return Err(SidecarError::ResolutionFailed(errors.join("; ")));
        }

        Ok(response.definitions.unwrap_or_default())
    }

    /// Resolve all types (explicit + inferred) in a single operation.
    ///
    /// # Arguments
    /// * `explicit` - Symbols for explicit type bundling
    /// * `infer` - Requests for type inference
    /// * `extraction_config` - Optional agent-generated unwrap rules
    ///
    /// # Returns
    /// Combined result with both explicit and inferred types.
    pub fn resolve_all_types(
        &self,
        explicit: &[SymbolRequest],
        infer: &[InferRequestItem],
        extraction_config: Option<&ExtractionConfig>,
    ) -> Result<TypeResolutionResult, SidecarError> {
        self.ensure_ready()?;

        let mut result = TypeResolutionResult {
            dts_content: None,
            explicit_manifest: vec![],
            inferred_types: vec![],
            symbol_failures: vec![],
            errors: vec![],
        };

        // Infer implicit types FIRST: a successful inference is the compiler's
        // view of the actual use site, and it carries the resolved array depth
        // relative to its anchor symbol. The explicit bundle below needs that
        // depth before it runs (#306).
        if !infer.is_empty() {
            let infer_response = self.infer_types(infer, extraction_config)?;
            if let Some(inferred) = infer_response.inferred_types {
                result.inferred_types = inferred;
            }
            if let Some(errors) = infer_response.errors {
                result.errors.extend(errors);
            }
        }

        // Two-anchor arbitration (#413, pub/sub only): a request carrying the
        // scanner's deterministic borrow witness whose alias the inference
        // resolved to a DIFFERENT named root is demoted here — re-aimed at
        // the tsc-witnessed root so the bundler defines the alias from the
        // inferred payload type instead of the borrowed symbol. This must
        // happen BEFORE the bundle runs: compat verdicts are computed from
        // the bundled dts, so a post-hoc flag flip in
        // `enrich_manifest_with_type_resolution` could never undo a wrong
        // explicit definition.
        let explicit = demote_witnessed_borrowed_anchors(explicit, &result.inferred_types);

        // Bundle explicit types. An LLM-extracted anchor is a bare identifier
        // by schema contract (`User[]` → `User`), so bundling it as-is erases
        // the use-site's array-ness and an array-vs-scalar mismatch scores
        // compatible (#306). Copy the inference-resolved depth onto each
        // matching request so the bundler's array_depth wrap (#248) restores
        // the `[]` levels.
        let explicit = apply_inferred_array_depth(&explicit, &result.inferred_types);
        if !explicit.is_empty() {
            let bundle_response = self.resolve_types(&explicit)?;
            result.dts_content = bundle_response.dts_content;
            if let Some(manifest) = bundle_response.manifest {
                result.explicit_manifest = manifest;
            }
            if let Some(failures) = bundle_response.symbol_failures {
                result.symbol_failures = failures;
            }
            if let Some(errors) = bundle_response.errors {
                result.errors.extend(errors);
            }
        }

        let had_explicit_dts = result.dts_content.is_some();
        let mut combined_dts = result.dts_content.take().unwrap_or_default();
        let mut appended_aliases: HashSet<String> = HashSet::new();

        // Pre-populate with aliases already defined by the bundler so the
        // infer / failure-fallback loops below never shadow them with `= unknown`.
        if had_explicit_dts {
            for req in &explicit {
                if let Some(alias) = &req.alias
                    && Self::dts_defines_alias(&combined_dts, alias)
                {
                    appended_aliases.insert(alias.clone());
                }
                if Self::dts_defines_alias(&combined_dts, &req.symbol_name) {
                    appended_aliases.insert(req.symbol_name.clone());
                }
            }
        }

        let mut append_alias = |alias: &str, type_string: &str| -> bool {
            if !appended_aliases.insert(alias.to_string()) {
                return false;
            }
            if !combined_dts.is_empty() && !combined_dts.ends_with('\n') {
                combined_dts.push('\n');
            }
            combined_dts.push_str("export type ");
            combined_dts.push_str(alias);
            combined_dts.push_str(" = ");
            combined_dts.push_str(type_string.trim().trim_end_matches(';'));
            combined_dts.push_str(";\n");
            true
        };

        let mut inferred_aliases = HashSet::new();
        for inferred in &result.inferred_types {
            inferred_aliases.insert(inferred.alias.clone());
            let type_string = if Self::is_untyped_response_type(&inferred.type_string) {
                "unknown"
            } else {
                inferred.type_string.as_str()
            };
            append_alias(&inferred.alias, type_string);
        }

        // Scrub inferred_types so downstream consumers (enrich_manifest_with_type_resolution)
        // see "unknown" for framework types and leave type_state as Unknown.
        for inferred in &mut result.inferred_types {
            if Self::is_untyped_response_type(&inferred.type_string) {
                inferred.type_string = "unknown".to_string();
            }
        }

        for failure in &result.symbol_failures {
            if let Some(request) = explicit.iter().find(|req| {
                req.symbol_name == failure.symbol_name && req.source_file == failure.source_file
            }) {
                let alias = request
                    .alias
                    .clone()
                    .unwrap_or_else(|| request.symbol_name.clone());
                append_alias(&alias, "unknown");
            }
        }

        if !infer.is_empty() {
            for request in infer {
                if let Some(alias) = &request.alias
                    && !inferred_aliases.contains(alias)
                {
                    append_alias(alias, "unknown");
                }
            }
        }

        if had_explicit_dts || !combined_dts.is_empty() {
            result.dts_content = Some(combined_dts);
        }

        Ok(result)
    }

    /// Check health status of the sidecar.
    pub fn health_check(&self) -> Result<SidecarResponse, SidecarError> {
        let request = SidecarRequest::Health {
            request_id: self.next_request_id(),
        };

        self.send_request(&request)?;
        self.read_response_with_timeout(Duration::from_secs(5))
    }

    /// Shutdown the sidecar gracefully.
    pub fn shutdown(&self) -> Result<(), SidecarError> {
        let request = SidecarRequest::Shutdown {
            request_id: self.next_request_id(),
        };

        // Send shutdown, ignore response (process will exit)
        let _ = self.send_request(&request);
        Ok(())
    }

    // ========================================================================
    // Internal Methods
    // ========================================================================

    fn next_request_id(&self) -> String {
        let mut counter = self.request_counter.lock().unwrap();
        *counter += 1;
        format!("req-{}", counter)
    }

    /// Check whether a bundled DTS string already defines a given alias
    /// (as a type, interface, class, enum, or namespace declaration).
    fn dts_defines_alias(content: &str, alias: &str) -> bool {
        let escaped = regex::escape(alias);
        let pattern = format!(r"\b(type|interface|class|enum|namespace)\s+{}\b", escaped);
        match regex::Regex::new(&pattern) {
            Ok(re) => re.is_match(content),
            Err(_) => false,
        }
    }

    fn is_untyped_response_type(type_string: &str) -> bool {
        let trimmed = type_string.trim().trim_end_matches(';');
        if trimmed.is_empty() {
            return false;
        }
        let base = trimmed.rsplit('.').next().unwrap_or(trimmed);
        matches!(
            base,
            // Express
            "Response" | "Request" | "NextFunction" |
            "Express" | "Application" | "Router" |
            // Fastify
            "Context" | "FastifyInstance" | "FastifyReply" | "FastifyRequest" |
            // Koa
            "Koa" | "ParameterizedContext" |
            // Hapi
            "ResponseToolkit" | "ResponseObject" | "Lifecycle" |
            // NestJS
            "ExecutionContext" | "ArgumentsHost" | "CallHandler" | "HttpException" |
            // Hono
            "Hono" | "HonoRequest" |
            // Node.js HTTP core
            "IncomingMessage" | "ServerResponse"
        )
    }

    fn ensure_ready(&self) -> Result<(), SidecarError> {
        let state = self.state.lock().unwrap();
        match &*state {
            SidecarState::Ready => Ok(()),
            SidecarState::Failed(e) => Err(SidecarError::NotReady(e.clone())),
            _ => Err(SidecarError::NotReady(
                "Sidecar not initialized. Call start_init() and wait_ready() first.".to_string(),
            )),
        }
    }

    fn send_request(&self, request: &SidecarRequest) -> Result<(), SidecarError> {
        let json = serde_json::to_string(request)
            .map_err(|e| SidecarError::SerializationError(e.to_string()))?;

        let mut stdin = self.stdin.lock().unwrap();
        writeln!(stdin, "{}", json).map_err(|e| SidecarError::IoError(e.to_string()))?;
        stdin
            .flush()
            .map_err(|e| SidecarError::IoError(e.to_string()))?;

        Ok(())
    }

    fn read_response_with_timeout(
        &self,
        timeout: Duration,
    ) -> Result<SidecarResponse, SidecarError> {
        let mut stdout = self.stdout.lock().unwrap();
        let mut line = String::new();

        // Set up timeout using a simple polling approach
        // Note: For production, consider using async I/O
        let start = Instant::now();

        loop {
            if start.elapsed() > timeout {
                return Err(SidecarError::Timeout);
            }

            // Try to read a line
            match stdout.read_line(&mut line) {
                Ok(0) => {
                    // EOF - process may have died
                    return Err(SidecarError::ProcessDied);
                }
                Ok(_) => {
                    // Got a line, parse it
                    let trimmed = line.trim();
                    if trimmed.is_empty() {
                        line.clear();
                        continue;
                    }

                    let response: SidecarResponse = serde_json::from_str(trimmed).map_err(|e| {
                        SidecarError::DeserializationError(format!("{}: {}", e, trimmed))
                    })?;

                    return Ok(response);
                }
                Err(ref e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                    // No data yet, sleep a bit
                    thread::sleep(Duration::from_millis(10));
                    continue;
                }
                Err(e) => {
                    return Err(SidecarError::IoError(e.to_string()));
                }
            }
        }
    }
}

/// Two-anchor arbitration for pub/sub payload anchors (#413, the #403/#359
/// borrow-class lineage): demote a witnessed-borrowed explicit request when
/// the same alias's location-based inference resolved a DIFFERENT named root.
///
/// A pub/sub op can carry two independent anchors: the LLM's explicit
/// `primary_type_symbol` (a judgment, measured wrong 13/20 on the honest
/// borrow fixture) and the payload locator, which the sidecar resolves
/// deterministically with tsc. When both resolve, the per-alias inferred root
/// symbol is compared against the explicit request's symbol — the same
/// alias+symbol join `apply_inferred_array_depth` performs. On a named-root
/// disagreement the explicit request is demoted: re-aimed at the inferred
/// root (symbol, declaration file, and array depth all from the inference),
/// so the bundler defines the alias from the tsc-witnessed payload type
/// instead of the borrowed one. Re-aiming rather than dropping keeps the
/// alias's dts definition self-contained — the inferred type_string keeps
/// named types as names (`OrderPlaced`), which would dangle if pasted in as
/// a standalone `export type` — while still making the inferred type the
/// alias's definition.
///
/// Demotion is gated on the scanner's deterministic borrow witness
/// (`payload_borrow_witness`, computed from the file's AST in
/// `collect_pubsub_type_requests`): no witness, no demotion — a bare
/// tsc-vs-LLM disagreement without AST evidence keeps the explicit symbol,
/// so a mis-anchored inference (wrong text occurrence, envelope resolution)
/// can never displace a correct explicit anchor on its own.
///
/// Anonymous inferred types are NOT arbitrated: when the inference returns a
/// structural type with no root symbol (`primary_type_symbol: None` — object
/// literals, encoded payloads, lib-global roots), the named-root-disagreement
/// rule cannot fire and the explicit symbol is kept, witness or not. There is
/// deliberately no resolution for that case — a structural shape carries no
/// identity to disagree with, and inventing a comparison (e.g. shape
/// equality) would demote on formatting noise.
///
/// Further keeps, all deliberate:
/// - an alias carried by more than one explicit request (fan-in ambiguity —
///   the inference cannot be attributed to either request);
/// - an inference whose type_string is not the bare named form of its own
///   root (`Root`, `Root[]`, …): a generic instantiation
///   (`Envelope<Order>`) or an expanded structural shape cannot be
///   reproduced by bundling the bare root symbol, so re-aiming would change
///   the type;
/// - a root with no reported declaration file (the bundler could not resolve
///   it), or a framework envelope root (demotion must never install
///   machinery as a payload);
/// - requests without the witness flag — every HTTP/socket/GraphQL request,
///   making this function structurally inert outside pub/sub.
fn demote_witnessed_borrowed_anchors(
    explicit: &[SymbolRequest],
    inferred: &[InferredType],
) -> Vec<SymbolRequest> {
    // First inference per alias wins, mirroring `apply_inferred_array_depth`
    // and the `or_insert` join in `enrich_manifest_with_type_resolution`.
    let mut inferred_by_alias: HashMap<&str, &InferredType> = HashMap::new();
    for inf in inferred {
        inferred_by_alias.entry(inf.alias.as_str()).or_insert(inf);
    }

    let mut alias_counts: HashMap<&str, usize> = HashMap::new();
    for req in explicit {
        if let Some(alias) = req.alias.as_deref() {
            *alias_counts.entry(alias).or_insert(0) += 1;
        }
    }

    explicit
        .iter()
        .map(|req| {
            if !req.payload_borrow_witness {
                return req.clone();
            }
            let Some(alias) = req.alias.as_deref() else {
                return req.clone();
            };
            if alias_counts.get(alias).copied().unwrap_or(0) > 1 {
                return req.clone();
            }
            let Some(inf) = inferred_by_alias.get(alias) else {
                return req.clone();
            };
            // Anonymous inferred type: no root to disagree with — keep.
            let Some(root) = inf.primary_type_symbol.as_deref() else {
                return req.clone();
            };
            if root == req.symbol_name {
                return req.clone();
            }
            // Re-aiming needs the root's declaration file.
            let Some(root_source) = inf.primary_type_symbol_source.as_deref() else {
                return req.clone();
            };
            // Never install machinery as a payload.
            if TypeSidecar::is_untyped_response_type(root) {
                return req.clone();
            }
            // The inference must BE the bare named form of its root (modulo
            // array suffixes), or bundling the root would change the type.
            let mut named_form = inf.type_string.trim();
            while let Some(stripped) = named_form.strip_suffix("[]") {
                named_form = stripped.trim_end();
            }
            if named_form != root {
                return req.clone();
            }
            info!(
                alias = %alias,
                explicit_symbol = %req.symbol_name,
                inferred_root = %root,
                inferred_root_source = %root_source,
                "[type_sidecar] pub/sub anchor arbitration: witnessed borrowed \
                 symbol disagrees with the tsc-resolved payload root; demoting \
                 the explicit anchor to the inferred type"
            );
            SymbolRequest {
                symbol_name: root.to_string(),
                source_file: root_source.to_string(),
                alias: req.alias.clone(),
                array_depth: inf.array_depth,
                payload_borrow_witness: false,
            }
        })
        .collect()
}

/// Copy inference-resolved array depths onto explicit symbol requests (#306).
///
/// An LLM-extracted anchor is a bare identifier by schema contract (`User[]` →
/// `User`), so an explicit bundle built from it erases the use-site's
/// array-ness: the producer comparand for a handler returning
/// `TimelineEvent[]` becomes the bare element and an array-vs-scalar mismatch
/// passes assignability. The inference that runs for the SAME alias resolves
/// the actual use site through ts-morph and reports the element symbol plus
/// the peeled depth, so when alias and symbol agree the depth is deterministic
/// ground truth for the request. Depths already set by the caller (the GraphQL
/// SDL list marker, #248) are never overwritten; a symbol disagreement means
/// the anchor doesn't describe the inferred type, so the request is left
/// untouched.
fn apply_inferred_array_depth(
    explicit: &[SymbolRequest],
    inferred: &[InferredType],
) -> Vec<SymbolRequest> {
    // First anchor-carrying inference per alias wins, mirroring the
    // `or_insert` join `enrich_manifest_with_type_resolution` uses.
    let mut depth_by_alias: HashMap<&str, (&str, u32)> = HashMap::new();
    for inf in inferred {
        if let (Some(symbol), Some(depth)) = (inf.primary_type_symbol.as_deref(), inf.array_depth)
            && depth > 0
        {
            depth_by_alias
                .entry(inf.alias.as_str())
                .or_insert((symbol, depth));
        }
    }

    explicit
        .iter()
        .cloned()
        .map(|mut req| {
            if req.array_depth.is_none()
                && let Some(alias) = req.alias.as_deref()
                && let Some((symbol, depth)) = depth_by_alias.get(alias)
                && *symbol == req.symbol_name
            {
                req.array_depth = Some(*depth);
            }
            req
        })
        .collect()
}

impl Drop for TypeSidecar {
    fn drop(&mut self) {
        debug!("[type_sidecar] Shutting down sidecar");

        // Try graceful shutdown first
        let _ = self.shutdown();

        // Give it a moment to exit
        thread::sleep(Duration::from_millis(100));

        // Force kill if still running
        let _ = self.child.kill();
    }
}

// ============================================================================
// Error Types
// ============================================================================

/// Errors that can occur when using the TypeSidecar
#[derive(Debug, Clone)]
pub enum SidecarError {
    /// Failed to spawn the sidecar process
    SpawnFailed(String),
    /// Sidecar initialization failed
    InitFailed(String),
    /// Sidecar is not ready to handle requests
    NotReady(String),
    /// Operation timed out
    Timeout,
    /// Sidecar process died unexpectedly
    ProcessDied,
    /// I/O error communicating with sidecar
    IoError(String),
    /// Failed to serialize request
    SerializationError(String),
    /// Failed to deserialize response
    DeserializationError(String),
    /// Definition resolution failed
    ResolutionFailed(String),
}

impl std::fmt::Display for SidecarError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SidecarError::SpawnFailed(e) => write!(f, "Failed to spawn sidecar: {}", e),
            SidecarError::InitFailed(e) => write!(f, "Sidecar initialization failed: {}", e),
            SidecarError::NotReady(e) => write!(f, "Sidecar not ready: {}", e),
            SidecarError::Timeout => write!(f, "Sidecar operation timed out"),
            SidecarError::ProcessDied => write!(f, "Sidecar process died unexpectedly"),
            SidecarError::IoError(e) => write!(f, "I/O error: {}", e),
            SidecarError::SerializationError(e) => write!(f, "Serialization error: {}", e),
            SidecarError::DeserializationError(e) => write!(f, "Deserialization error: {}", e),
            SidecarError::ResolutionFailed(e) => write!(f, "Definition resolution failed: {}", e),
        }
    }
}

impl std::error::Error for SidecarError {}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_infer_kind_serialization() {
        let kind = InferKind::FunctionReturn;
        let json = serde_json::to_string(&kind).unwrap();
        assert_eq!(json, r#""function_return""#);

        let kind = InferKind::ResponseBody;
        let json = serde_json::to_string(&kind).unwrap();
        assert_eq!(json, r#""response_body""#);

        let kind = InferKind::RequestBody;
        let json = serde_json::to_string(&kind).unwrap();
        assert_eq!(json, r#""request_body""#);
    }

    #[test]
    fn test_symbol_request_serialization() {
        let request = SymbolRequest {
            symbol_name: "User".to_string(),
            source_file: "src/types.ts".to_string(),
            alias: Some("UserResponse".to_string()),
            array_depth: None,
            payload_borrow_witness: false,
        };
        let json = serde_json::to_string(&request).unwrap();
        assert!(json.contains(r#""symbol_name":"User""#));
        // array_depth defaults to None and is skipped on the wire.
        assert!(!json.contains("array_depth"));
        assert!(json.contains(r#""alias":"UserResponse""#));
    }

    #[test]
    fn test_infer_request_serialization() {
        let request = InferRequestItem {
            file_path: "src/routes.ts".to_string(),
            line_number: 42,
            span_start: Some(128),
            span_end: Some(196),
            expression_text: None,
            expression_line: None,
            infer_kind: InferKind::ResponseBody,
            alias: None,
            param_name: None,
        };
        let json = serde_json::to_string(&request).unwrap();
        assert!(json.contains(r#""file_path":"src/routes.ts""#));
        assert!(json.contains(r#""line_number":42"#));
        assert!(json.contains(r#""span_start":128"#));
        assert!(json.contains(r#""span_end":196"#));
        assert!(json.contains(r#""infer_kind":"response_body""#));
        assert!(!json.contains("alias")); // Should be skipped when None
    }

    #[test]
    fn test_sidecar_request_init_serialization() {
        let request = SidecarRequest::Init {
            request_id: "req-1".to_string(),
            repo_root: "/path/to/repo".to_string(),
            tsconfig_path: Some("tsconfig.json".to_string()),
        };
        let json = serde_json::to_string(&request).unwrap();
        assert!(json.contains(r#""action":"init""#));
        assert!(json.contains(r#""request_id":"req-1""#));
        assert!(json.contains(r#""repo_root":"/path/to/repo""#));
    }

    #[test]
    fn test_sidecar_request_bundle_serialization() {
        let request = SidecarRequest::Bundle {
            request_id: "req-2".to_string(),
            symbols: vec![SymbolRequest {
                symbol_name: "User".to_string(),
                source_file: "src/types.ts".to_string(),
                alias: None,
                array_depth: None,
                payload_borrow_witness: false,
            }],
        };
        let json = serde_json::to_string(&request).unwrap();
        assert!(json.contains(r#""action":"bundle""#));
        assert!(json.contains(r#""symbols""#));
    }

    #[test]
    fn test_sidecar_response_deserialization() {
        let json = r#"{
            "request_id": "req-1",
            "status": "ready",
            "init_time_ms": 500
        }"#;
        let response: SidecarResponse = serde_json::from_str(json).unwrap();
        assert_eq!(response.request_id, "req-1");
        assert_eq!(response.status, "ready");
        assert_eq!(response.init_time_ms, Some(500));
    }

    #[test]
    fn test_sidecar_state_equality() {
        assert_eq!(SidecarState::Ready, SidecarState::Ready);
        assert_ne!(SidecarState::Ready, SidecarState::Spawning);
        assert_eq!(
            SidecarState::Failed("error".to_string()),
            SidecarState::Failed("error".to_string())
        );
    }

    fn symbol_request(symbol: &str, alias: &str, array_depth: Option<u32>) -> SymbolRequest {
        SymbolRequest {
            symbol_name: symbol.to_string(),
            source_file: "src/types.ts".to_string(),
            alias: Some(alias.to_string()),
            array_depth,
            payload_borrow_witness: false,
        }
    }

    fn inferred(alias: &str, symbol: Option<&str>, array_depth: Option<u32>) -> InferredType {
        InferredType {
            alias: alias.to_string(),
            type_string: "{ at: string; }[]".to_string(),
            is_explicit: false,
            source_location: SourceLocation {
                file_path: "src/server.ts".to_string(),
                start_line: 13,
                end_line: 16,
                start_column: None,
                end_column: None,
            },
            infer_kind: InferKind::FunctionReturn,
            primary_type_symbol: symbol.map(str::to_string),
            array_depth,
            primary_type_symbol_source: None,
        }
    }

    /// #306: the timeline shape. The LLM anchor is the bare element
    /// (`TimelineEvent` from `TimelineEvent[]`), so the explicit bundle would
    /// erase the array; the same-alias inference resolved the use site to the
    /// element symbol at depth 1, which must be copied onto the request.
    #[test]
    fn inferred_array_depth_wraps_matching_explicit_request() {
        let explicit = vec![symbol_request("TimelineEvent", "Alias_Response", None)];
        let inferred = vec![inferred("Alias_Response", Some("TimelineEvent"), Some(1))];

        let adjusted = apply_inferred_array_depth(&explicit, &inferred);

        assert_eq!(adjusted[0].array_depth, Some(1));
    }

    /// A depth the caller already set (the GraphQL SDL list marker, #248) is
    /// authoritative — the inference join must never overwrite it.
    #[test]
    fn inferred_array_depth_never_overwrites_caller_depth() {
        let explicit = vec![symbol_request("Order", "Alias_Response", Some(2))];
        let inferred = vec![inferred("Alias_Response", Some("Order"), Some(1))];

        let adjusted = apply_inferred_array_depth(&explicit, &inferred);

        assert_eq!(adjusted[0].array_depth, Some(2));
    }

    /// A symbol disagreement means the inferred type is not "an array of the
    /// requested anchor", so the request must stay untouched.
    #[test]
    fn inferred_array_depth_requires_symbol_agreement() {
        let explicit = vec![symbol_request("TimelineEvent", "Alias_Response", None)];
        let inferred = vec![inferred("Alias_Response", Some("SomethingElse"), Some(1))];

        let adjusted = apply_inferred_array_depth(&explicit, &inferred);

        assert_eq!(adjusted[0].array_depth, None);
    }

    /// A scalar inference (no array_depth on the wire) and a different-alias
    /// inference both leave the request as-is.
    #[test]
    fn inferred_array_depth_ignores_scalars_and_other_aliases() {
        let explicit = vec![
            symbol_request("TimelineEntry", "Scalar_Response", None),
            symbol_request("TimelineEvent", "Unrelated_Response", None),
        ];
        let inferred = vec![
            inferred("Scalar_Response", Some("TimelineEntry"), None),
            inferred("Other_Response", Some("TimelineEvent"), Some(1)),
        ];

        let adjusted = apply_inferred_array_depth(&explicit, &inferred);

        assert_eq!(adjusted[0].array_depth, None);
        assert_eq!(adjusted[1].array_depth, None);
    }

    // ---- #413 two-anchor arbitration (pub/sub borrow demotion) ----

    fn witnessed(mut req: SymbolRequest) -> SymbolRequest {
        req.payload_borrow_witness = true;
        req
    }

    fn inferred_with_anchor(
        alias: &str,
        symbol: Option<&str>,
        type_string: &str,
        symbol_source: Option<&str>,
    ) -> InferredType {
        let mut inf = inferred(alias, symbol, None);
        inf.type_string = type_string.to_string();
        inf.primary_type_symbol_source = symbol_source.map(str::to_string);
        inf
    }

    /// Witnessed wrong symbol + named-root disagreement + bare named inferred
    /// form → the explicit request is demoted: re-aimed at the inferred root
    /// (symbol + declaration file), so the bundler defines the alias from the
    /// tsc-witnessed payload type.
    #[test]
    fn arbitration_demotes_witnessed_wrong_symbol() {
        let explicit = vec![witnessed(symbol_request(
            "AuditRecord",
            "Alias_Response",
            None,
        ))];
        let inferred = vec![inferred_with_anchor(
            "Alias_Response",
            Some("OrderPlaced"),
            "OrderPlaced",
            Some("/repo/src/orders.ts"),
        )];

        let kept = demote_witnessed_borrowed_anchors(&explicit, &inferred);

        assert_eq!(kept.len(), 1);
        assert_eq!(kept[0].symbol_name, "OrderPlaced", "re-aimed at the root");
        assert_eq!(kept[0].source_file, "/repo/src/orders.ts");
        assert_eq!(kept[0].alias.as_deref(), Some("Alias_Response"));
        assert_eq!(kept[0].array_depth, None);
        assert!(!kept[0].payload_borrow_witness, "witness consumed");
    }

    /// An array-form inference (`Root[]`) demotes with the inferred depth so
    /// the bundler's array wrap restores the `[]` levels.
    #[test]
    fn arbitration_demotes_array_form_with_depth() {
        let explicit = vec![witnessed(symbol_request(
            "AuditRecord",
            "Alias_Response",
            None,
        ))];
        let mut inf = inferred_with_anchor(
            "Alias_Response",
            Some("OrderPlaced"),
            "OrderPlaced[]",
            Some("/repo/src/orders.ts"),
        );
        inf.array_depth = Some(1);
        let inferred = vec![inf];

        let kept = demote_witnessed_borrowed_anchors(&explicit, &inferred);

        assert_eq!(kept[0].symbol_name, "OrderPlaced");
        assert_eq!(kept[0].array_depth, Some(1));
    }

    /// The same disagreement WITHOUT the scanner's borrow witness keeps the
    /// explicit request: a bare tsc-vs-LLM disagreement never demotes.
    #[test]
    fn arbitration_keeps_unwitnessed_disagreement() {
        let explicit = vec![symbol_request("AuditRecord", "Alias_Response", None)];
        let inferred = vec![inferred_with_anchor(
            "Alias_Response",
            Some("OrderPlaced"),
            "OrderPlaced",
            Some("/repo/src/orders.ts"),
        )];

        let kept = demote_witnessed_borrowed_anchors(&explicit, &inferred);

        assert_eq!(kept.len(), 1);
        assert_eq!(kept[0].symbol_name, "AuditRecord");
    }

    /// Root agreement keeps the explicit request even with a witness (the
    /// witness was evidently wrong or vacuous — tsc confirms the anchor).
    #[test]
    fn arbitration_keeps_agreement() {
        let explicit = vec![witnessed(symbol_request(
            "OrderPlaced",
            "Alias_Response",
            None,
        ))];
        let inferred = vec![inferred_with_anchor(
            "Alias_Response",
            Some("OrderPlaced"),
            "OrderPlaced",
            Some("/repo/src/orders.ts"),
        )];

        let kept = demote_witnessed_borrowed_anchors(&explicit, &inferred);

        assert_eq!(kept.len(), 1);
        assert_eq!(kept[0].symbol_name, "OrderPlaced");
        assert_eq!(kept[0].source_file, "src/types.ts", "request untouched");
    }

    /// Anonymous inferred type (no root symbol): the named-root-disagreement
    /// rule cannot fire, so the explicit symbol is kept — witness or not.
    /// There is deliberately no resolution for this case.
    #[test]
    fn arbitration_keeps_explicit_on_anonymous_inference() {
        let explicit = vec![witnessed(symbol_request(
            "OrderPlaced",
            "Alias_Response",
            None,
        ))];
        let inferred = vec![inferred_with_anchor(
            "Alias_Response",
            None,
            "{ id: string; }",
            None,
        )];

        let kept = demote_witnessed_borrowed_anchors(&explicit, &inferred);

        assert_eq!(kept.len(), 1);
        assert_eq!(kept[0].symbol_name, "OrderPlaced");
    }

    /// A disagreeing inference whose type_string is not the bare named form
    /// of its root (generic instantiation, expanded structural shape) never
    /// demotes: bundling the bare root would change the type. Same for a
    /// missing declaration source or a framework-machinery root.
    #[test]
    fn arbitration_keeps_explicit_when_reaim_would_change_the_type() {
        let cases: Vec<InferredType> = vec![
            // Generic instantiation: bundling bare `Envelope` loses the arg.
            inferred_with_anchor(
                "Alias_Response",
                Some("Envelope"),
                "Envelope<OrderPlaced>",
                Some("/repo/src/types.ts"),
            ),
            // Structural expansion with a named root: not the bare form.
            inferred_with_anchor(
                "Alias_Response",
                Some("OrderPlaced"),
                "{ id: string; }",
                Some("/repo/src/orders.ts"),
            ),
            // No declaration source: the bundler could not resolve the root.
            inferred_with_anchor("Alias_Response", Some("OrderPlaced"), "OrderPlaced", None),
            // Framework machinery root.
            inferred_with_anchor(
                "Alias_Response",
                Some("FastifyReply"),
                "FastifyReply",
                Some("/repo/node_modules/fastify/types.d.ts"),
            ),
        ];
        for inf in cases {
            let explicit = vec![witnessed(symbol_request(
                "AuditRecord",
                "Alias_Response",
                None,
            ))];
            let type_string = inf.type_string.clone();
            let kept = demote_witnessed_borrowed_anchors(&explicit, &[inf]);

            assert_eq!(kept.len(), 1);
            assert_eq!(
                kept[0].symbol_name, "AuditRecord",
                "shape {type_string:?} must not demote"
            );
        }
    }

    /// An alias carried by more than one explicit request is fan-in
    /// ambiguous: the inference cannot be attributed, so nothing is demoted.
    #[test]
    fn arbitration_keeps_fan_in_ambiguous_alias() {
        let explicit = vec![
            witnessed(symbol_request("AuditRecord", "Alias_Response", None)),
            symbol_request("OtherThing", "Alias_Response", None),
        ];
        let inferred = vec![inferred_with_anchor(
            "Alias_Response",
            Some("OrderPlaced"),
            "OrderPlaced",
            Some("/repo/src/orders.ts"),
        )];

        let kept = demote_witnessed_borrowed_anchors(&explicit, &inferred);

        assert_eq!(kept.len(), 2);
        assert_eq!(kept[0].symbol_name, "AuditRecord");
        assert_eq!(kept[1].symbol_name, "OtherThing");
    }

    /// No inference for the alias at all → keep (nothing to arbitrate with).
    #[test]
    fn arbitration_keeps_explicit_without_matching_inference() {
        let explicit = vec![witnessed(symbol_request(
            "AuditRecord",
            "Alias_Response",
            None,
        ))];
        let inferred = vec![inferred_with_anchor(
            "Other_Response",
            Some("OrderPlaced"),
            "OrderPlaced",
            Some("/repo/src/orders.ts"),
        )];

        let kept = demote_witnessed_borrowed_anchors(&explicit, &inferred);

        assert_eq!(kept.len(), 1);
        assert_eq!(kept[0].symbol_name, "AuditRecord");
    }

    #[test]
    fn test_dts_defines_alias_matches_interface() {
        let dts = "export interface Endpoint_abc_Response {\n  id: string;\n}\n";
        assert!(TypeSidecar::dts_defines_alias(dts, "Endpoint_abc_Response"));
    }

    #[test]
    fn test_dts_defines_alias_matches_type() {
        let dts = "export type Endpoint_abc_Response = { id: string };\n";
        assert!(TypeSidecar::dts_defines_alias(dts, "Endpoint_abc_Response"));
    }

    #[test]
    fn test_dts_defines_alias_no_false_positive() {
        let dts = "export interface Endpoint_abc_Request {\n  id: string;\n}\n";
        assert!(!TypeSidecar::dts_defines_alias(
            dts,
            "Endpoint_abc_Response"
        ));
    }

    #[test]
    fn test_dts_defines_alias_matches_enum() {
        let dts = "export enum Status { Active, Inactive }\n";
        assert!(TypeSidecar::dts_defines_alias(dts, "Status"));
    }

    #[test]
    fn test_is_untyped_response_type() {
        assert!(TypeSidecar::is_untyped_response_type("Response"));
        assert!(TypeSidecar::is_untyped_response_type("express.Response"));
        assert!(TypeSidecar::is_untyped_response_type("FastifyReply"));
        assert!(!TypeSidecar::is_untyped_response_type("{ id: string }"));
        assert!(!TypeSidecar::is_untyped_response_type("UserResponse"));
    }

    /// Verify that resolve_all_types does not append `type X = unknown` when
    /// the bundler already produced an `interface X { ... }` in the DTS.
    #[test]
    fn test_resolve_all_types_no_duplicate_when_bundled() {
        // Simulate a TypeResolutionResult as if the bundler already produced content.
        let bundled_dts = concat!(
            "export interface Endpoint_abc_Response {\n",
            "  id: string;\n",
            "  author: string;\n",
            "}\n"
        );

        // Build an equivalent of what resolve_all_types does post-bundle/infer:
        let had_explicit_dts = true;
        let combined_dts = bundled_dts.to_string();
        let mut appended_aliases: HashSet<String> = HashSet::new();

        // This is the new pre-population logic under test:
        let explicit = vec![SymbolRequest {
            symbol_name: "SomeInterface".to_string(),
            source_file: "src/types.ts".to_string(),
            alias: Some("Endpoint_abc_Response".to_string()),
            array_depth: None,
            payload_borrow_witness: false,
        }];

        if had_explicit_dts {
            for req in &explicit {
                if let Some(alias) = &req.alias
                    && TypeSidecar::dts_defines_alias(&combined_dts, alias)
                {
                    appended_aliases.insert(alias.clone());
                }
                if TypeSidecar::dts_defines_alias(&combined_dts, &req.symbol_name) {
                    appended_aliases.insert(req.symbol_name.clone());
                }
            }
        }

        // Now simulate the infer loop trying to append unknown for the same alias
        let inferred_alias = "Endpoint_abc_Response";
        let already_present = !appended_aliases.insert(inferred_alias.to_string());
        assert!(
            already_present,
            "appended_aliases should already contain the bundled alias"
        );

        // The combined DTS should NOT contain a duplicate `type X = unknown`
        assert!(
            !combined_dts.contains("type Endpoint_abc_Response = unknown"),
            "Should not have appended unknown fallback for already-bundled alias"
        );
        assert_eq!(
            combined_dts.matches("Endpoint_abc_Response").count(),
            1,
            "Alias should appear exactly once in bundled DTS"
        );
    }
}
