/**
 * External-dependency pinning from an installed repo's node_modules — the
 * yarn/bun coverage gap. Lockfile parsing covers npm and pnpm only; on a
 * yarn (classic or berry) or bun repo the emitted surface's externals ended
 * up unpinned and every edge through them abstained at check, even though
 * the repo's own node_modules carried the exact installed versions.
 *
 * Pins:
 *  1. installed repo with ONLY a yarn.lock still pins: versions come from
 *     node_modules/<pkg>/package.json (no lockfile parser involved);
 *  2. bare repo + npm lockfile is unchanged (lockfile fallback regression);
 *  3. workspace-member symlink guard: a node_modules entry whose realpath
 *     lands inside the repo but outside every node_modules directory is a
 *     linked-in workspace sibling with an unpublished version — never
 *     pinned from node_modules (pnpm's .pnpm indirection stays pinnable);
 *  4. precedence: when node_modules and the lockfile disagree, the
 *     installed version wins — it is what the repo resolves against;
 *  5. corrupt or missing node_modules/<pkg>/package.json degrades to the
 *     lockfile fallback (or unpinned) without crashing;
 *  6. non-published version strings (workspace:*, 0.0.0-use.local) are
 *     never pins — a pin the registry cannot satisfy would fail the whole
 *     synthetic-workspace install at check time.
 */

import { describe, it } from 'node:test';
import * as assert from 'node:assert';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { captureStub } from '../src/capture/index.js';
import { installedVersions } from '../src/capture/lockfile.js';

function tempDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'carrick-installed-pin-'));
}

function writeTree(root: string, files: Record<string, string>): string {
  fs.mkdirSync(root, { recursive: true });
  for (const [name, text] of Object.entries(files)) {
    const p = path.join(root, name);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, text);
  }
  return root;
}

const TSCONFIG = JSON.stringify({
  compilerOptions: {
    target: 'ES2020',
    module: 'commonjs',
    strict: true,
    skipLibCheck: true,
    rootDir: 'src',
  },
  include: ['src'],
});

/** Yarn-berry-ish lockfile. Never parsed by the sidecar — its presence just
 * documents that the fixture repo has no npm/pnpm lockfile to fall back on. */
const YARN_LOCK = [
  '# This file is generated by running "yarn install" inside your project.',
  '__metadata:',
  '  version: 8',
  '',
  '"fakedep@npm:^3.0.0":',
  '  version: 3.2.1',
  '',
].join('\n');

const SERVICE_TS = [
  "import type { FakeThing } from 'fakedep';",
  '',
  'export interface GadgetResponse {',
  '  thing: FakeThing;',
  '  fetchedAt: string;',
  '}',
  '',
].join('\n');

const FAKEDEP_DTS = 'export interface FakeThing {\n  id: string;\n  weight: number;\n}\n';

const GADGET_ANCHOR = {
  kind: 'symbol',
  alias: 'Endpoint_gadget_Response',
  symbol_name: 'GadgetResponse',
  source_file: 'src/service.ts',
  anchor_origin: 'llm-symbol',
} as const;

describe('installedVersions (unit)', () => {
  it('pins plain and scoped packages from node_modules package.json', () => {
    const repo = writeTree(tempDir(), {
      'node_modules/fakedep/package.json': JSON.stringify({
        name: 'fakedep',
        version: '3.2.1',
      }),
      'node_modules/@scope/pkg/package.json': JSON.stringify({
        name: '@scope/pkg',
        version: '1.0.0-beta.2',
      }),
    });
    const versions = installedVersions(repo, ['fakedep', '@scope/pkg', 'absent']);
    assert.strictEqual(versions.get('fakedep'), '3.2.1');
    assert.strictEqual(versions.get('@scope/pkg'), '1.0.0-beta.2');
    assert.strictEqual(versions.get('absent'), undefined);
  });

  it('follows the pnpm .pnpm indirection (symlink into node_modules is pinnable)', () => {
    const repo = writeTree(tempDir(), {
      'node_modules/.pnpm/fakedep@2.5.0/node_modules/fakedep/package.json': JSON.stringify({
        name: 'fakedep',
        version: '2.5.0',
      }),
    });
    fs.symlinkSync(
      path.join(repo, 'node_modules', '.pnpm', 'fakedep@2.5.0', 'node_modules', 'fakedep'),
      path.join(repo, 'node_modules', 'fakedep'),
      'dir'
    );
    assert.strictEqual(installedVersions(repo, ['fakedep']).get('fakedep'), '2.5.0');
  });

  it('skips a workspace-member symlink (inside the repo, outside node_modules)', () => {
    const repo = writeTree(tempDir(), {
      'packages/models/package.json': JSON.stringify({
        name: '@ws/models',
        version: '0.5.0',
      }),
      'node_modules/.keep': '',
    });
    fs.mkdirSync(path.join(repo, 'node_modules', '@ws'), { recursive: true });
    fs.symlinkSync(
      path.join(repo, 'packages', 'models'),
      path.join(repo, 'node_modules', '@ws', 'models'),
      'dir'
    );
    assert.strictEqual(installedVersions(repo, ['@ws/models']).get('@ws/models'), undefined);
  });

  it('skips a symlink that leaves the repo entirely (npm link to a dev checkout)', () => {
    const outside = writeTree(tempDir(), {
      'linked-lib/package.json': JSON.stringify({ name: 'linked-lib', version: '9.0.0' }),
    });
    const repo = writeTree(tempDir(), { 'node_modules/.keep': '' });
    fs.symlinkSync(
      path.join(outside, 'linked-lib'),
      path.join(repo, 'node_modules', 'linked-lib'),
      'dir'
    );
    assert.strictEqual(
      installedVersions(repo, ['linked-lib']).get('linked-lib'),
      undefined
    );
  });

  it('treats corrupt or missing package.json as unpinned, without crashing', () => {
    const repo = writeTree(tempDir(), {
      'node_modules/corrupt/package.json': '{ this is not json',
      'node_modules/nomanifest/index.d.ts': 'export {};\n',
    });
    const versions = installedVersions(repo, ['corrupt', 'nomanifest']);
    assert.strictEqual(versions.size, 0);
  });

  it('rejects version strings the registry cannot satisfy', () => {
    const repo = writeTree(tempDir(), {
      'node_modules/wsproto/package.json': JSON.stringify({
        name: 'wsproto',
        version: 'workspace:*',
      }),
      'node_modules/uselocal/package.json': JSON.stringify({
        name: 'uselocal',
        version: '0.0.0-use.local',
      }),
    });
    assert.strictEqual(installedVersions(repo, ['wsproto', 'uselocal']).size, 0);
  });

  it('returns nothing on a bare checkout (no node_modules)', () => {
    assert.strictEqual(installedVersions(tempDir(), ['fakedep']).size, 0);
  });
});

describe('capture v2: pins from installed node_modules with lockfile fallback', () => {
  it('installed repo with only a yarn.lock pins from node_modules (the coverage gap)', () => {
    const root = tempDir();
    const repoRoot = writeTree(path.join(root, 'repo'), {
      'tsconfig.json': TSCONFIG,
      'yarn.lock': YARN_LOCK,
      'src/service.ts': SERVICE_TS,
      'node_modules/fakedep/package.json': JSON.stringify({
        name: 'fakedep',
        version: '3.2.1',
        types: 'index.d.ts',
      }),
      'node_modules/fakedep/index.d.ts': FAKEDEP_DTS,
    });
    const result = captureStub({
      repoRoot,
      serviceName: 'yarn-installed-svc',
      outDir: path.join(root, 'stub'),
      anchors: [GADGET_ANCHOR],
    });
    assert.strictEqual(result.success, true, JSON.stringify(result.errors));
    assert.strictEqual(result.bare_checkout, false);
    assert.deepStrictEqual(result.pinned_dependencies, { fakedep: '3.2.1' });
    assert.deepStrictEqual(result.unpinned_externals, []);
    const rec = result.aliases.find((a) => a.alias === 'Endpoint_gadget_Response')!;
    assert.strictEqual(rec.self_check, 'ok', rec.self_check_detail);
  });

  it('bare repo + npm lockfile still pins from the lockfile (regression)', () => {
    const root = tempDir();
    const repoRoot = writeTree(path.join(root, 'repo'), {
      'tsconfig.json': TSCONFIG,
      'src/service.ts': SERVICE_TS,
      'package-lock.json': JSON.stringify({
        lockfileVersion: 3,
        packages: { '': {}, 'node_modules/fakedep': { version: '9.9.9' } },
      }),
    });
    const result = captureStub({
      repoRoot,
      serviceName: 'bare-lockfile-svc',
      outDir: path.join(root, 'stub'),
      anchors: [GADGET_ANCHOR],
    });
    assert.strictEqual(result.success, true, JSON.stringify(result.errors));
    assert.strictEqual(result.bare_checkout, true);
    assert.deepStrictEqual(result.pinned_dependencies, { fakedep: '9.9.9' });
    assert.deepStrictEqual(result.unpinned_externals, []);
  });

  it('workspace-member symlink is never pinned from node_modules', () => {
    const root = tempDir();
    const repoRoot = writeTree(path.join(root, 'repo'), {
      'tsconfig.json': TSCONFIG,
      'yarn.lock': YARN_LOCK,
      'src/service.ts': [
        "import type { MemberDto } from '@ws/models';",
        '',
        'export interface GadgetResponse {',
        '  member: MemberDto;',
        '}',
        '',
      ].join('\n'),
      'packages/models/package.json': JSON.stringify({
        name: '@ws/models',
        version: '0.5.0',
        types: 'index.d.ts',
      }),
      'packages/models/index.d.ts': 'export interface MemberDto {\n  id: string;\n}\n',
      'node_modules/.keep': '',
    });
    fs.mkdirSync(path.join(repoRoot, 'node_modules', '@ws'), { recursive: true });
    fs.symlinkSync(
      path.join(repoRoot, 'packages', 'models'),
      path.join(repoRoot, 'node_modules', '@ws', 'models'),
      'dir'
    );
    const result = captureStub({
      repoRoot,
      serviceName: 'workspace-link-svc',
      outDir: path.join(root, 'stub'),
      anchors: [GADGET_ANCHOR],
    });
    assert.strictEqual(result.success, true, JSON.stringify(result.errors));
    // No lockfile version either, so the member stays honestly unpinned
    // (fail-closed abstain downstream), never pinned at 0.5.0.
    assert.deepStrictEqual(result.pinned_dependencies, {});
    assert.deepStrictEqual(result.unpinned_externals, ['@ws/models']);
  });

  it('node_modules wins when the npm lockfile disagrees on the version', () => {
    const root = tempDir();
    const repoRoot = writeTree(path.join(root, 'repo'), {
      'tsconfig.json': TSCONFIG,
      'src/service.ts': SERVICE_TS,
      'package-lock.json': JSON.stringify({
        lockfileVersion: 3,
        packages: { '': {}, 'node_modules/fakedep': { version: '1.0.0' } },
      }),
      'node_modules/fakedep/package.json': JSON.stringify({
        name: 'fakedep',
        version: '2.0.0',
        types: 'index.d.ts',
      }),
      'node_modules/fakedep/index.d.ts': FAKEDEP_DTS,
    });
    const result = captureStub({
      repoRoot,
      serviceName: 'disagree-svc',
      outDir: path.join(root, 'stub'),
      anchors: [GADGET_ANCHOR],
    });
    assert.strictEqual(result.success, true, JSON.stringify(result.errors));
    assert.deepStrictEqual(result.pinned_dependencies, { fakedep: '2.0.0' });
  });

  it('corrupt node_modules package.json falls back to the lockfile, no crash', () => {
    const root = tempDir();
    const repoRoot = writeTree(path.join(root, 'repo'), {
      'tsconfig.json': TSCONFIG,
      'src/service.ts': SERVICE_TS,
      'package-lock.json': JSON.stringify({
        lockfileVersion: 3,
        packages: { '': {}, 'node_modules/fakedep': { version: '1.2.3' } },
      }),
      'node_modules/fakedep/package.json': '{ this is not json',
    });
    const result = captureStub({
      repoRoot,
      serviceName: 'corrupt-manifest-svc',
      outDir: path.join(root, 'stub'),
      anchors: [GADGET_ANCHOR],
    });
    assert.strictEqual(result.success, true, JSON.stringify(result.errors));
    assert.deepStrictEqual(result.pinned_dependencies, { fakedep: '1.2.3' });
  });
});
