/**
 * Surface Emitter - Emits .d.ts surface files with rewritten module specifiers
 *
 * This module replaces the previous dts-bundle-generator approach with a
 * ts-morph-based AST transformation and emission pipeline.
 *
 * Key features:
 * - Does NOT bundle dependencies (unlike dts-bundle-generator)
 * - Rewrites module specifiers to repo-specific aliases (@carrick/{repoName}/{spec})
 * - Handles ImportDeclaration, ImportTypeNode, and ExportDeclaration
 * - Supports scoped packages and subpaths
 * - Includes a safety pass for any compiler-introduced raw specifiers
 */

import {
  Project,
  SourceFile,
  Node,
  SyntaxKind,
  type ImportDeclaration,
  type ExportDeclaration,
  type ImportTypeNode,
  type StringLiteral,
} from 'ts-morph';
import * as path from 'node:path';
import * as fs from 'node:fs';
import type {
  PayloadDefinition,
  SurfaceEmitResult,
  SurfaceManifestEntry,
  SymbolRequest,
  BundleResult,
  ManifestEntry,
  SymbolFailure,
} from './types.js';

/**
 * Options for SurfaceEmitter construction
 */
export interface SurfaceEmitterOptions {
  /** The ts-morph Project instance */
  project: Project;
  /** The repository root directory (absolute path) */
  repoRoot: string;
}

/**
 * Options for TypeBundler construction (legacy)
 */
export interface TypeBundlerOptions {
  /** The ts-morph Project instance */
  project: Project;
  /** The repository root directory (absolute path) */
  repoRoot: string;
}

/**
 * SurfaceEmitter - Generates .d.ts surface files with rewritten imports
 *
 * Usage:
 *   const emitter = new SurfaceEmitter({ project, repoRoot });
 *   const result = emitter.emit(repoName, payloads, outputPath);
 */
export class SurfaceEmitter {
  private readonly project: Project;
  private readonly repoRoot: string;

  constructor(options: SurfaceEmitterOptions) {
    this.project = options.project;
    this.repoRoot = options.repoRoot;
  }

  /**
   * Emit a surface .d.ts file containing payload type declarations
   *
   * @param repoName - Repository name for specifier rewriting
   * @param payloads - Payload definitions to include
   * @param outputPath - Path to write the surface file
   * @returns SurfaceEmitResult
   */
  emit(
    repoName: string,
    payloads: PayloadDefinition[],
    outputPath: string
  ): SurfaceEmitResult {
    const errors: string[] = [];
    const manifest: SurfaceManifestEntry[] = [];

    try {
      // Phase 1: Generate surface content as a string
      const surfaceLines: string[] = [
        '// Generated surface file for type compatibility checking',
        '// Do not edit - this file is auto-generated by Carrick',
        '',
      ];

      // Collect all import specifiers we need to track for rewriting
      const importSpecifiers = new Set<string>();

      // Phase 2: Add payload type declarations
      for (const payload of payloads) {
        const { alias, type_string, source_file } = payload;

        // Analyze type string for import references
        const detectedImports = this.extractImportReferences(type_string);
        for (const imp of detectedImports) {
          importSpecifiers.add(imp);
        }

        // Add type alias declaration
        surfaceLines.push(`export type ${alias} = ${type_string};`);
        surfaceLines.push('');

        manifest.push({
          alias,
          type_string,
          rewritten_imports: [],
        });
      }

      // Phase 3: Create a temporary source file for AST manipulation
      const tempFileName = `__carrick_surface_${repoName}_${Date.now()}.d.ts`;
      const tempFilePath = path.join(this.repoRoot, tempFileName);
      const initialContent = surfaceLines.join('\n');

      const tempSourceFile = this.project.createSourceFile(
        tempFilePath,
        initialContent,
        { overwrite: true }
      );

      // Phase 4: Rewrite module specifiers in the AST
      const rewrittenImports = this.rewriteModuleSpecifiers(tempSourceFile, repoName);

      // Update manifest with rewritten imports
      for (const entry of manifest) {
        entry.rewritten_imports = rewrittenImports;
      }

      // Phase 5: Get the transformed content
      let surfaceContent = tempSourceFile.getFullText();

      // Phase 6: Safety pass - catch any raw specifiers the compiler might have added
      surfaceContent = this.safetyRewritePass(surfaceContent, repoName);

      // Phase 7: Clean up temporary source file from project
      this.project.removeSourceFile(tempSourceFile);

      // Phase 8: Write output file
      const absoluteOutputPath = path.isAbsolute(outputPath)
        ? outputPath
        : path.join(this.repoRoot, outputPath);

      // Ensure directory exists
      const outputDir = path.dirname(absoluteOutputPath);
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      fs.writeFileSync(absoluteOutputPath, surfaceContent, 'utf-8');
      this.log(`Emitted surface file: ${absoluteOutputPath}`);

      return {
        success: true,
        surface_content: surfaceContent,
        output_path: absoluteOutputPath,
        manifest,
      };
    } catch (err) {
      const error = err instanceof Error ? err.message : String(err);
      this.logError(`Surface emission failed: ${error}`);
      errors.push(error);

      return {
        success: false,
        errors,
      };
    }
  }

  /**
   * Extract potential import references from a type string.
   * These are module specifiers that might need rewriting.
   */
  private extractImportReferences(typeString: string): string[] {
    const imports: string[] = [];

    // Match import("...") syntax
    const importTypeRegex = /import\s*\(\s*["']([^"']+)["']\s*\)/g;
    let match: RegExpExecArray | null;
    while ((match = importTypeRegex.exec(typeString)) !== null) {
      imports.push(match[1]);
    }

    // Match from "..." syntax (in case of inline imports)
    const fromRegex = /from\s+["']([^"']+)["']/g;
    while ((match = fromRegex.exec(typeString)) !== null) {
      imports.push(match[1]);
    }

    return imports;
  }

  /**
   * Rewrite all module specifiers in a source file to use repo-scoped aliases.
   *
   * Targets:
   * 1. ImportDeclaration.moduleSpecifier
   * 2. ImportTypeNode argument (import("..."))
   * 3. ExportDeclaration.moduleSpecifier
   *
   * @returns Array of rewritten specifiers
   */
  private rewriteModuleSpecifiers(sourceFile: SourceFile, repoName: string): string[] {
    const rewrittenSpecifiers: string[] = [];

    // 1. Rewrite ImportDeclaration specifiers
    const importDecls = sourceFile.getImportDeclarations();
    for (const importDecl of importDecls) {
      const specifier = importDecl.getModuleSpecifierValue();
      if (this.shouldRewriteSpecifier(specifier)) {
        const newSpecifier = this.rewriteSpecifier(specifier, repoName);
        importDecl.setModuleSpecifier(newSpecifier);
        rewrittenSpecifiers.push(`${specifier} → ${newSpecifier}`);
      }
    }

    // 2. Rewrite ExportDeclaration specifiers
    const exportDecls = sourceFile.getExportDeclarations();
    for (const exportDecl of exportDecls) {
      const specifier = exportDecl.getModuleSpecifierValue();
      if (specifier && this.shouldRewriteSpecifier(specifier)) {
        const newSpecifier = this.rewriteSpecifier(specifier, repoName);
        exportDecl.setModuleSpecifier(newSpecifier);
        rewrittenSpecifiers.push(`${specifier} → ${newSpecifier}`);
      }
    }

    // 3. Rewrite ImportTypeNode arguments
    // These appear in type positions: import("module").Type
    sourceFile.forEachDescendant((node) => {
      if (Node.isImportTypeNode(node)) {
        const arg = node.getArgument();
        if (Node.isLiteralTypeNode(arg)) {
          const literal = arg.getLiteral();
          if (Node.isStringLiteral(literal)) {
            const specifier = literal.getLiteralValue();
            if (this.shouldRewriteSpecifier(specifier)) {
              const newSpecifier = this.rewriteSpecifier(specifier, repoName);
              literal.setLiteralValue(newSpecifier);
              rewrittenSpecifiers.push(`${specifier} → ${newSpecifier}`);
            }
          }
        }
      }
    });

    return rewrittenSpecifiers;
  }

  /**
   * Determine if a module specifier should be rewritten.
   * Only non-relative specifiers should be rewritten.
   */
  private shouldRewriteSpecifier(specifier: string): boolean {
    // Don't rewrite relative imports
    if (specifier.startsWith('./') || specifier.startsWith('../')) {
      return false;
    }

    // Don't rewrite already-rewritten specifiers
    if (specifier.startsWith('@carrick/')) {
      return false;
    }

    // Don't rewrite node built-ins
    if (specifier.startsWith('node:')) {
      return false;
    }

    // Some common node built-ins without prefix
    const nodeBuiltins = [
      'fs', 'path', 'os', 'util', 'events', 'stream', 'http', 'https',
      'url', 'querystring', 'crypto', 'buffer', 'child_process', 'cluster',
      'dgram', 'dns', 'net', 'readline', 'tls', 'tty', 'zlib', 'assert',
      'async_hooks', 'console', 'constants', 'domain', 'inspector', 'module',
      'perf_hooks', 'process', 'punycode', 'string_decoder', 'timers',
      'trace_events', 'v8', 'vm', 'worker_threads'
    ];
    if (nodeBuiltins.includes(specifier) || nodeBuiltins.includes(specifier.split('/')[0])) {
      return false;
    }

    return true;
  }

  /**
   * Rewrite a module specifier to the repo-scoped format.
   *
   * Format: @carrick/{repoName}/{originalSpecifier}
   *
   * Preserves:
   * - Scoped packages: "@scope/pkg" → "@carrick/repo-a/@scope/pkg"
   * - Subpaths: "zod/lib/helpers" → "@carrick/repo-a/zod/lib/helpers"
   * - Combined: "@scope/pkg/subpath" → "@carrick/repo-a/@scope/pkg/subpath"
   */
  private rewriteSpecifier(specifier: string, repoName: string): string {
    return `@carrick/${repoName}/${specifier}`;
  }

  /**
   * Safety pass: Scan emitted content for any raw specifiers that might have
   * been introduced by the TypeScript compiler and rewrite them.
   *
   * This catches edge cases where the compiler emits types with their original
   * module specifiers that weren't caught by AST traversal.
   */
  private safetyRewritePass(content: string, repoName: string): string {
    // Common patterns to catch:
    // - from "package"
    // - import("package")
    // - export * from "package"

    // We need to be careful not to double-rewrite @carrick/ specifiers

    // Pattern for import("...") that's not already @carrick
    const importTypePattern = /import\s*\(\s*["'](?!@carrick\/|\.\.?\/|node:)([^"']+)["']\s*\)/g;
    content = content.replace(importTypePattern, (match, specifier) => {
      const newSpecifier = this.rewriteSpecifier(specifier, repoName);
      return match.replace(`"${specifier}"`, `"${newSpecifier}"`).replace(`'${specifier}'`, `'${newSpecifier}'`);
    });

    // Pattern for from "..." that's not already @carrick
    const fromPattern = /from\s+["'](?!@carrick\/|\.\.?\/|node:)([^"']+)["']/g;
    content = content.replace(fromPattern, (match, specifier) => {
      const newSpecifier = this.rewriteSpecifier(specifier, repoName);
      return match.replace(`"${specifier}"`, `"${newSpecifier}"`).replace(`'${specifier}'`, `'${newSpecifier}'`);
    });

    return content;
  }

  /**
   * Log a message to stderr
   */
  private log(message: string): void {
    console.error(`[sidecar:surface-emitter] ${message}`);
  }

  /**
   * Log an error to stderr
   */
  private logError(message: string): void {
    console.error(`[sidecar:surface-emitter:error] ${message}`);
  }
}

// =============================================================================
// Legacy TypeBundler (kept for backwards compatibility during migration)
// =============================================================================

/**
 * TypeBundler - Legacy bundler using simpler approach
 *
 * This is a simplified replacement that doesn't use dts-bundle-generator.
 * It extracts type definitions directly using ts-morph.
 *
 * @deprecated Use SurfaceEmitter instead for the new architecture
 */
export class TypeBundler {
  private readonly project: Project;
  private readonly repoRoot: string;

  constructor(options: TypeBundlerOptions) {
    this.project = options.project;
    this.repoRoot = options.repoRoot;
  }

  /**
   * Bundle the requested symbols into type definitions
   *
   * @param symbols - Array of symbol requests to bundle
   * @returns BundleResult with the bundled content or errors
   */
  bundle(symbols: SymbolRequest[]): BundleResult {
    const manifest: ManifestEntry[] = [];
    const symbolFailures: SymbolFailure[] = [];
    const errors: string[] = [];

    // Dedupe symbols
    const uniqueSymbols = this.dedupeSymbols(symbols);

    // Validate all symbols exist
    const validatedSymbols = this.validateSymbols(uniqueSymbols, symbolFailures);

    if (validatedSymbols.length === 0) {
      return {
        success: false,
        symbol_failures: symbolFailures,
        errors: symbolFailures.length > 0
          ? ['All requested symbols failed to resolve']
          : ['No symbols provided'],
      };
    }

    try {
      // Generate type definitions directly
      const dtsLines: string[] = [
        '// Generated by Carrick TypeBundler',
        '// This file contains extracted type definitions',
        '',
      ];

      for (const symbol of validatedSymbols) {
        const typeInfo = this.extractTypeDefinition(symbol);

        if (typeInfo) {
          dtsLines.push(typeInfo.definition);
          dtsLines.push('');

          manifest.push({
            alias: symbol.alias || symbol.symbol_name,
            original_name: symbol.symbol_name,
            source_file: symbol.source_file,
            type_string: typeInfo.typeString,
            is_explicit: true,
          });
        } else {
          symbolFailures.push({
            symbol_name: symbol.symbol_name,
            source_file: symbol.source_file,
            reason: `Could not extract type definition for '${symbol.symbol_name}'`,
          });
        }
      }

      const dtsContent = dtsLines.join('\n');

      return {
        success: true,
        dts_content: dtsContent,
        manifest,
        symbol_failures: symbolFailures.length > 0 ? symbolFailures : undefined,
      };
    } catch (err) {
      const error = err instanceof Error ? err.message : String(err);
      this.logError(`Bundle generation failed: ${error}`);
      errors.push(error);

      return {
        success: false,
        symbol_failures: symbolFailures.length > 0 ? symbolFailures : undefined,
        errors,
      };
    }
  }

  private dedupeSymbols(symbols: SymbolRequest[]): SymbolRequest[] {
    const seen = new Set<string>();
    const unique: SymbolRequest[] = [];

    for (const symbol of symbols) {
      const key = `${symbol.source_file}::${symbol.symbol_name}::${symbol.alias || ''}`;
      if (seen.has(key)) {
        continue;
      }
      seen.add(key);
      unique.push(symbol);
    }

    return unique;
  }

  private validateSymbols(
    symbols: SymbolRequest[],
    failures: SymbolFailure[]
  ): SymbolRequest[] {
    const validated: SymbolRequest[] = [];

    for (const symbol of symbols) {
      const result = this.validateSymbol(symbol);

      if (result.valid) {
        validated.push(symbol);
      } else {
        failures.push({
          symbol_name: symbol.symbol_name,
          source_file: symbol.source_file,
          reason: result.reason || 'Unknown error',
        });
      }
    }

    return validated;
  }

  private validateSymbol(
    symbol: SymbolRequest
  ): { valid: boolean; reason?: string } {
    if (this.isPlaceholderSource(symbol.source_file)) {
      return {
        valid: false,
        reason: `Unsupported source placeholder: ${symbol.source_file}`,
      };
    }

    if (!this.isPathSource(symbol.source_file)) {
      return { valid: true };
    }

    // Resolve the source file path
    const absolutePath = path.isAbsolute(symbol.source_file)
      ? symbol.source_file
      : path.resolve(this.repoRoot, symbol.source_file);

    // Check if file exists
    if (!fs.existsSync(absolutePath)) {
      return {
        valid: false,
        reason: `Source file not found: ${symbol.source_file}`,
      };
    }

    // Get or add the source file to the project
    let sourceFile: SourceFile | undefined;
    try {
      sourceFile =
        this.project.getSourceFile(absolutePath) ||
        this.project.addSourceFileAtPath(absolutePath);
    } catch (err) {
      return {
        valid: false,
        reason: `Failed to load source file: ${err instanceof Error ? err.message : String(err)}`,
      };
    }

    // Look for the symbol in the file
    const symbolName = symbol.symbol_name;

    // Check interfaces
    if (sourceFile.getInterface(symbolName)) return { valid: true };

    // Check type aliases
    if (sourceFile.getTypeAlias(symbolName)) return { valid: true };

    // Check classes
    if (sourceFile.getClass(symbolName)) return { valid: true };

    // Check enums
    if (sourceFile.getEnum(symbolName)) return { valid: true };

    // Check exported variables
    if (sourceFile.getVariableDeclaration(symbolName)) return { valid: true };

    // Check functions
    if (sourceFile.getFunction(symbolName)) return { valid: true };

    // Symbol not found
    return {
      valid: false,
      reason: `Symbol '${symbolName}' not found in ${symbol.source_file}`,
    };
  }

  private extractTypeDefinition(
    symbol: SymbolRequest
  ): { definition: string; typeString: string } | null {
    const absolutePath = path.isAbsolute(symbol.source_file)
      ? symbol.source_file
      : path.resolve(this.repoRoot, symbol.source_file);

    const sourceFile = this.project.getSourceFile(absolutePath);
    if (!sourceFile) {
      return null;
    }

    const symbolName = symbol.symbol_name;
    const alias = symbol.alias || symbolName;

    // Try interface
    const iface = sourceFile.getInterface(symbolName);
    if (iface) {
      const text = iface.getText();
      const typeString = text;
      const alreadyExported = text.trimStart().startsWith('export');
      const definition = alias !== symbolName
        ? (alreadyExported
            ? text.replace(`interface ${symbolName}`, `interface ${alias}`)
            : text.replace(`interface ${symbolName}`, `export interface ${alias}`))
        : alreadyExported
          ? text
          : `export ${text}`;
      return { definition, typeString };
    }

    // Try type alias
    const typeAlias = sourceFile.getTypeAlias(symbolName);
    if (typeAlias) {
      const text = typeAlias.getText();
      const typeString = typeAlias.getType().getText();
      const alreadyExported = text.trimStart().startsWith('export');
      const definition = alias !== symbolName
        ? (alreadyExported
            ? text.replace(`type ${symbolName}`, `type ${alias}`)
            : text.replace(`type ${symbolName}`, `export type ${alias}`))
        : alreadyExported
          ? text
          : `export ${text}`;
      return { definition, typeString };
    }

    // Try class
    const classDecl = sourceFile.getClass(symbolName);
    if (classDecl) {
      const text = classDecl.getText();
      const typeString = text;
      const alreadyExported = text.trimStart().startsWith('export');
      const definition = alias !== symbolName
        ? (alreadyExported
            ? text.replace(`class ${symbolName}`, `declare class ${alias}`)
            : text.replace(`class ${symbolName}`, `export declare class ${alias}`))
        : alreadyExported
          ? text
          : `export declare ${text}`;
      return { definition, typeString };
    }

    // Try enum
    const enumDecl = sourceFile.getEnum(symbolName);
    if (enumDecl) {
      const text = enumDecl.getText();
      const typeString = text;
      const alreadyExported = text.trimStart().startsWith('export');
      const definition = alias !== symbolName
        ? (alreadyExported
            ? text.replace(`enum ${symbolName}`, `enum ${alias}`)
            : text.replace(`enum ${symbolName}`, `export enum ${alias}`))
        : alreadyExported
          ? text
          : `export ${text}`;
      return { definition, typeString };
    }

    // Try variable (const type definitions)
    const varDecl = sourceFile.getVariableDeclaration(symbolName);
    if (varDecl) {
      const type = varDecl.getType();
      const typeString = type.getText();
      const definition = `export type ${alias} = ${typeString};`;
      return { definition, typeString };
    }

    // Try function
    const funcDecl = sourceFile.getFunction(symbolName);
    if (funcDecl) {
      const text = funcDecl.getText();
      const typeString = text;
      const alreadyExported = text.trimStart().startsWith('export');
      const definition = alias !== symbolName
        ? (alreadyExported
            ? text.replace(`function ${symbolName}`, `declare function ${alias}`)
            : text.replace(`function ${symbolName}`, `export declare function ${alias}`))
        : alreadyExported
          ? text
          : `export declare ${text}`;
      return { definition, typeString };
    }

    return null;
  }

  private isPathSource(sourceFile: string): boolean {
    if (
      sourceFile.startsWith('.') ||
      sourceFile.startsWith('/') ||
      path.isAbsolute(sourceFile)
    ) {
      return true;
    }

    const basePath = path.resolve(this.repoRoot, sourceFile);
    if (fs.existsSync(basePath)) {
      return true;
    }

    if (path.extname(sourceFile) !== '') {
      return false;
    }

    const extensions = ['.ts', '.tsx', '.js', '.jsx', '.d.ts'];
    return extensions.some((ext) => fs.existsSync(basePath + ext));
  }

  private isPlaceholderSource(sourceFile: string): boolean {
    const trimmed = sourceFile.trim();
    return trimmed === '' || trimmed === '%none%' || trimmed === '%inline%';
  }

  private log(message: string): void {
    console.error(`[sidecar:bundler] ${message}`);
  }

  private logError(message: string): void {
    console.error(`[sidecar:bundler:error] ${message}`);
  }
}
