name: Carrick

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  test-published-action:
    name: Test Published Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Carrick Analysis on entire repo
        id: carrick-analysis
        uses: daveymoores/carrick@v1
        with:
          carrick-org: ${{ secrets.CARRICK_ORG }}
          carrick-api-key: ${{ secrets.CARRICK_API_KEY }}

      - name: Comment PR with Carrick Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          COMMENT_BODY: ${{ steps.carrick-analysis.outputs.pr-comment }}
        with:
          script: |
            const comment = process.env.COMMENT_BODY;

            if (comment && comment.trim() !== '') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            } else {
              console.log('No comment content to post');
            }
