name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Build binary
        env:
          CARRICK_API_ENDPOINT: ${{ secrets.CARRICK_API_ENDPOINT }}
          CARRICK_LAMBDA_URL: ${{ secrets.CARRICK_API_ENDPOINT }}/types/check-or-upload

        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Create release archive
        run: |
          mkdir -p release
          cp target/x86_64-unknown-linux-gnu/release/carrick release/
          cp -r ts_check release/
          cd release
          tar -czf carrick-action-linux.tar.gz carrick ts_check

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: release/carrick-action-linux.tar.gz
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
